language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex .travis-ci.sh
env:
  - OPAM_SWITCH=system
  - OPAM_SWITCH=3.12.1
  - OPAM_SWITCH=4.01.0
  - OPAM_SWITCH=4.02.2
  - OPAM_SWITCH=4.03.0
cache:
  directories:
  - $HOME/.opam
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f47ff4ebe702f6acd4e0
    on_success: always
    on_failure: always
    on_start: never
